### ISSUE TITLE
Brightness value range is wrong

### ISSUE THREAD

**Issue by JimTheGhost** [boeyum/WizLan#1]
The dimmer is near unusable because the value seems to go from -400 to 10000 which makes it hard to use in tagged flows

**Comment by boeyum** [comment]
Yes, I am aware of the error and are test a correction these days. The reason is a mix up with Homey's default dimming that uses a different value set than expected. There are two flow cards for dimming, and one of them goes from 0 - 100 %. In the version of the app in Test, Homey's Defautl Dimming Flow Card has been removed.

**Comment by boeyum** [comment]
The issue should be fixed in the latest version of the app, which was posted on the Homey shop a few days ago. Source will be posted here soon.

**Comment by boeyum** [comment]
After 2 weeks of new version in production, and monitoring, this error appears to be corrected.
