### ISSUE TITLE
Cannot add device

### ISSUE THREAD

**Issue by KetilHaa** [boeyum/WizLan#2]
I have tried to add Philips wiz color lamp to the previous version of wiz lan app. Always get this message: Error: unknown_error_getting_file.
Tried again today after update to v 1.1.0 - same error.
Works fine on wiz connected.
Android phone, homey pro 2019.
Best regards, Ketil

**Comment by boeyum** [comment]
The app is only tested against light bulbs from the company Wiz Connected. Since this is a local API that uses a JSON API against UDP communication, I expect that there is something there that does not match Philips Wiz color lamps. As far as I understand after searching the web, the wiz light bulbs from Philips are an older version of the interface. My app was developed against light bulbs from the company Wiz Connected since I have not had access to Philips light bulbs.

**Comment by KetilHaa** [comment]
Ok, takk. Trodde Philips wiz og Wiz var ett og samme. Med vennlig hilsenKetil Rygg Haanæsmobil 909 86 738 2. sep. 2024 11:09 skrev Jan-Ivar Bøyum ***@***.***>:
The app is only tested against light bulbs from the company Wiz Connected. Since this is a local API that uses a JSON API against UDP communication, I expect that there is something there that does not match Philips Wiz color lamps. As far as I understand after searching the web, the wiz light bulbs from Philips are an older version of the interface. My app was developed against light bulbs from the company Wiz Connected since I have not had access to Philips light bulbs.

**Comment by boeyum** [comment]
The app is designed for light bulbs from wizconnected.com. These can be purchased in Norway from several stores (such as the Elektroimportøren).
