### ISSUE TITLE
Can not get the app to fully work

### ISSUE THREAD

**Issue by briandonna** [boeyum/WizLan#3]
I can not get the to do anything but turn on and off, the dim or the color will not work. Can you help please?

When I try to dim the fixture it will work once but will not work agene after that unless I turn it off and back on agene and then it will work once and not after that, its the same if I try to change the color temperature. The only thing that works all the time is the on and off.

Below is the Homey Diagnostics Report if that helps.

34cd2660-f297-4a80-9332-8fc4b15dd280

**Comment by boeyum** [comment]
Sorry late reply, I've been on vacation. I have looked through the diagnosis of the report, and after that tested with both a color light bulb and a tunable light bulb. Both seemed to function normally here in my environment (Homey Pro 2023). Both dimming and color worked as normal. Just to be sure, the light bulbs you use are from Wiz Connected (Philips Wiz doesn't work)? If you haven't made it work and you have more information then contact me.

**Comment by briandonna** [comment]
No, I have not been able to get the lights to work no matter what I do.
 
Yes, my lights are Wiz lights, I have 28-color downlights Model #604298 and 12-Wiz LED 40W B12 color Candle-Shaped bulb (I do not have the Model number).
 
Right now all but one is being run by the Homey app "WiZ connect" by Drenso V.O.F and all the light works Perfactly on that app. I have one running on your app for testing and that one will only turn on and off consistently, the dimming and color changing will not work properly, it will only dim once and change color once and then you have to turn it off and back on to do it again, I have tried to delete that one light from its zone with the "Wiz connect" app to try to separate from the other app and zone and then reinstall it using your app with its own zone just to test it and it still will not work properly.
 
I am completely out of ideas as to what to do to get your app to work and I so what it to work as I am not a fan of the cloud. Can you suggest or give me an idea of what you might need from me to troubleshoot?
 
Could the homey "Wiz connect" app be interfering with your app in any way? I have so many light bulbs to delete them all, and add them all to your app just to test and find out if the two apps are interfering with each other is a lot of work, and if it turns out that I still have the same problem and have to reinstall the back to the old app would be a lot. Have you tried to have the homey "Wiz connect" app present with your app to see if your app is affected?
 
The below is the apps that I am running right now with Homey if that helps in any way. 
Ciradian Lighting, Colo Tools (But not using this one Eufy Security, Everything Smart, Google Nest, HomeKit Controller, Lutron Caseta, Samsung SmartThings, Shelly, Wiz Connected, & Wiz Lan
 
Thank you so much for your time and help! :)
Brian

**Comment by boeyum** [comment]
I'm not quite sure, but think I may have found something similar to your problem. In connection with trying to find out why Wiz light bulbs sold via Philips do not work, I managed to obtain a bulb via a dealer in Norway. At the same time, I got hold of an older Wiz Connected bulb from Denmark. Since I have developed a test environment in Java (IntelliJ Platform) that I use for analysis of the interface, I tested it there. It turned out that in principle, the interfaces are similar, but both of these bulbs had almost twice as long response time as the Wiz Connected light bulbs I otherwise use. It seems that the MSU (processor) or software in it is slowing it down. I managed to connect the Philips Wiz Light bulb to the app but the functionality was not as expected. I am now looking at solutions, and hope to test next week. When I solved the problem, I will post a new version of the app.    
**Attention.** I believe that a heavily loaded network may also cause the same response time problem so a change the app can solve the problem in this regard.
Jan-Ivar

**Comment by briandonna** [comment]
Hi Boeyum,

Have you made any progress on updating the app to accommodate my Wiz bulbs here in the US? Last we talked you were working on updating the app to work with these bulbs. 
Thank you for your time.
Brian

**Comment by boeyum** [comment]
I posted a new app today. I have managed to obtain a Wiz light bulb from the brand Philips, and this has been tested with that version. It appears that the problem with light bulbs supplied by Philips has a slower response time than those supplied by Wiz Connected. It has therefore been adjusted to timeout in the access library in the app. A heavily loaded network can therefore cause problems, as the app had major problems if I increased the timeout more than I have done. I hope the latest version of the app can help you. I wish you luck.
