### ISSUE TITLE
Unknown_error_getting_file

### ISSUE THREAD

**Issue by Lejland** [boeyum/WizLan#4]
Can install any bulbs. I have a Homey pro 2019. I have reinstalled the app and restarted it, but i still get the same issue as showed on the picture. I have created a dianosticreport as well: 3f20ee30-3129-4dca-b862-f6767551bed6
![Screenshot from 2024-09-10 11-28-51](https://github.com/user-attachments/assets/9fa04811-adb3-48a4-b3d8-1cfc3aecc7b7)

**Comment by boeyum** [comment]
Sorry it has taken time to answer, but I have been away on vacation. I cannot find any errors from what you have sent, and therefore have to answer a little in general. The IP address entered must be in the local WiFi network (the same as Homey is connected). If not, routing must be set up between the networks. In addition, the light bulbs must be of the type that comes from Wiz Connected and not from Philips Wiz. The reason for this is that Philips light bulbs appear to have differences in the interface so that it works with the local API I have developed. Since I have not been able to obtain light bulbs from Philips Wiz, I have not had the opportunity to take these into account.
